services:
  - type: web
    name: ijwi-autism-care
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    domains:
      - ijwi-autisme.ambabazi.tech
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false